# Generated by Django 3.1.7 on 2021-04-12 13:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import galleries.validators


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('galleries', '0003_auto_20210406_1728'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mediaupload',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mediaupload',
            name='tags',
            field=models.CharField(blank=True, max_length=500, validators=[galleries.validators.validate_tags_format]),
        ),
        migrations.AlterField(
            model_name='mediaupload',
            name='artist',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='mediaupload',
            name='file',
            field=models.FileField(upload_to='', validators=[galleries.validators.validate_media_file_extension]),
        ),
        migrations.AlterField(
            model_name='mediaupload',
            name='title',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
