# Generated by Django 3.1.7 on 2021-04-12 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galleries', '0004_auto_20210412_0904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='title',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='mediaupload',
            name='albums',
            field=models.ManyToManyField(blank=True, null=True, to='galleries.Album'),
        ),
        migrations.AlterField(
            model_name='mediaupload',
            name='artist',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='mediaupload',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
