# Generated by Django 3.1.7 on 2021-04-13 03:49

from django.db import migrations, models
import galleries.validators


class Migration(migrations.Migration):

    dependencies = [
        ('galleries', '0005_auto_20210412_0940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='title',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mediaupload',
            name='albums',
            field=models.ManyToManyField(blank=True, to='galleries.Album'),
        ),
        migrations.AlterField(
            model_name='mediaupload',
            name='artist',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mediaupload',
            name='tags',
            field=models.CharField(max_length=500, validators=[galleries.validators.validate_tags_format]),
        ),
        migrations.AlterField(
            model_name='mediaupload',
            name='title',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
