# Generated by Django 3.1.7 on 2021-04-13 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galleries', '0006_auto_20210412_2349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediaupload',
            name='artist',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='mediaupload',
            name='tags',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='mediaupload',
            name='title',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
