# Generated by Django 3.1.7 on 2021-04-30 23:03

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('galleries', '0007_auto_20210412_2359'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='album',
            unique_together={('owner', 'title')},
        ),
    ]
